FROM ldez/traefik-certs-dumper:v2.7.0-arm.v7

LABEL maintainer="Humenius <contact@humenius.me>"

COPY --from=multiarch/qemu-user-static:x86_64-arm /usr/bin/qemu-arm-static /usr/bin/qemu-arm-static

RUN \
    apk update && \
    apk add --no-cache \
        inotify-tools \
        util-linux \
        bash

COPY run.sh /

RUN ["chmod", "+x", "/run.sh"]

VOLUME ["/traefik"]
VOLUME ["/output"]

ENTRYPOINT ["/run.sh"]
